updated workflow

diff --git a/.github/workflows/terraform-initialization.yml b/.github/workflows/terraform-initialization.yml
--- a/.github/workflows/terraform-initialization.yml
+++ b/.github/workflows/terraform-initialization.yml
@@ -105,7 +105,6 @@ jobs:
             -var="auto_merge_pr=false"
             -target=module.vpc
             -target=module.eks
-            #-target=module.aws_auth_config
             -var="initialize_run=true"
           )
           
@@ -156,8 +155,6 @@ jobs:
             -var-file="../environments/${{ github.event.inputs.env }}/terraform.tfvars"
             -var="aws_region=$AWS_REGION"
             -var="github_token=$TOKEN_GITHUB"
-            #-target=module.vpc
-            #-var="initialize_run=true"
           )
           
           case "${{ github.event.inputs.action }}" in
@@ -182,14 +179,73 @@ jobs:
               ;;
           esac
     
-      # - name: Step 3 - Targeted Main Infrastructure - accept peering
+      - name: Step 3 - Targeted Main Infrastructure - accept peering
+        env:
+          AWS_REGION: ${{ env.AWS_REGION }}
+          PROVIDER_GITHUB_ARN: ${{ secrets.PROVIDER_GITHUB_ARN }}
+          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+        run: |
+          echo "================================================"
+          echo "STEP 3: Targeted Main Infrastructure accept peering"
+          echo "Environment: ${{ github.event.inputs.env }}"
+          echo "================================================"
+
+          cd terraform-main/main/
+          
+          terraform init -backend-config=../environments/${{ github.event.inputs.env }}/backend.config
+
+          COMMON_VARS=(
+            -var-file="../environments/${{ github.event.inputs.env }}/terraform.tfvars"
+            -var="github_token=$TOKEN_GITHUB"
+            -var="aws_region=$AWS_REGION"
+            -var="aws_iam_openid_connect_provider_github_arn=$PROVIDER_GITHUB_ARN"
+            -var="github_oidc_role_arn=$AWS_ROLE_TO_ASSUME"
+            -var="argocd_app_id=$ARGOCD_APP_ID"
+            -var="argocd_installation_id=$ARGOCD_INSTALLATION_ID"
+            -var="argocd_private_key_b64=$ARGOCD_PRIVATE_KEY_B64"
+            -var="github_oauth_client_id=$OAUTH_GITHUB_CLIENT_ID"
+            -var="github_oauth_client_secret=$OAUTH_GITHUB_CLIENT_SECRET"
+            -var="bootstrap_mode=false"
+            -var="update_apps=false"
+            -var="auto_merge_pr=false"
+            #-target=module.vpc_peering_acceptance
+            
+            -target=module.aws_auth_config
+            -target=module.security_groups
+            -var="initialize_run=false"
+          )
+          
+          case "${{ github.event.inputs.action }}" in
+            plan)
+              terraform plan "${COMMON_VARS[@]}"
+              ;;
+            apply)
+              echo "step -3 - applying!"
+              terraform apply -auto-approve "${COMMON_VARS[@]}"
+              ;;
+            plan-and-apply)
+              terraform plan "${COMMON_VARS[@]}"
+              echo "================================================"
+              echo "Plan complete. Proceeding with apply..."
+              echo "================================================"
+              terraform apply -auto-approve "${COMMON_VARS[@]}"
+              ;;
+            # destroy)
+            #   terraform destroy -auto-approve "${COMMON_VARS[@]}"
+            #   ;;
+            *)
+              echo "Invalid action: ${{ github.event.inputs.action }}"; exit 1
+              ;;
+          esac
+
+      # - name: Step 3e - Targeted Main Infrastructure - extras
       #   env:
       #     AWS_REGION: ${{ env.AWS_REGION }}
       #     PROVIDER_GITHUB_ARN: ${{ secrets.PROVIDER_GITHUB_ARN }}
       #     AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
       #   run: |
       #     echo "================================================"
-      #     echo "STEP 3: Targeted Main Infrastructure accept peering"
+      #     echo "STEP 3: Targeted Main Infrastructure extras"
       #     echo "Environment: ${{ github.event.inputs.env }}"
       #     echo "================================================"
 
@@ -222,64 +278,6 @@ jobs:
       #         terraform plan "${COMMON_VARS[@]}"
       #         ;;
       #       apply)
-      #         echo "step -3 - applying!"
-      #         terraform apply -auto-approve "${COMMON_VARS[@]}"
-      #         ;;
-      #       plan-and-apply)
-      #         terraform plan "${COMMON_VARS[@]}"
-      #         echo "================================================"
-      #         echo "Plan complete. Proceeding with apply..."
-      #         echo "================================================"
-      #         terraform apply -auto-approve "${COMMON_VARS[@]}"
-      #         ;;
-      #       # destroy)
-      #       #   terraform destroy -auto-approve "${COMMON_VARS[@]}"
-      #       #   ;;
-      #       *)
-      #         echo "Invalid action: ${{ github.event.inputs.action }}"; exit 1
-      #         ;;
-      #     esac
-
-      # - name: Step 3e - Targeted Main Infrastructure - extras
-      #   env:
-      #     AWS_REGION: ${{ env.AWS_REGION }}
-      #     PROVIDER_GITHUB_ARN: ${{ secrets.PROVIDER_GITHUB_ARN }}
-      #     AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-      #   run: |
-      #     echo "================================================"
-      #     echo "STEP 3: Targeted Main Infrastructure extras"
-      #     echo "Environment: ${{ github.event.inputs.env }}"
-      #     echo "================================================"
-
-      #     cd terraform-main/main/
-          
-      #     terraform init -backend-config=../environments/${{ github.event.inputs.env }}/backend.config
-
-      #     COMMON_VARS=(
-      #       -var-file="../environments/${{ github.event.inputs.env }}/terraform.tfvars"
-      #       -var="github_token=$TOKEN_GITHUB"
-      #       -var="aws_region=$AWS_REGION"
-      #       -var="aws_iam_openid_connect_provider_github_arn=$PROVIDER_GITHUB_ARN"
-      #       -var="github_oidc_role_arn=$AWS_ROLE_TO_ASSUME"
-      #       -var="argocd_app_id=$ARGOCD_APP_ID"
-      #       -var="argocd_installation_id=$ARGOCD_INSTALLATION_ID"
-      #       -var="argocd_private_key_b64=$ARGOCD_PRIVATE_KEY_B64"
-      #       -var="github_oauth_client_id=$OAUTH_GITHUB_CLIENT_ID"
-      #       -var="github_oauth_client_secret=$OAUTH_GITHUB_CLIENT_SECRET"
-      #       -var="bootstrap_mode=false"
-      #       -var="update_apps=false"
-      #       -var="auto_merge_pr=false"
-      #       -target=module.vpc_peering_acceptance
-      #       -target=module.security_groups
-      #       #-target=module.aws_auth_config
-      #       -var="initialize_run=false"
-      #     )
-          
-      #     case "${{ github.event.inputs.action }}" in
-      #       plan)
-      #         terraform plan "${COMMON_VARS[@]}"
-      #         ;;
-      #       apply)
       #         echo "step -3extras - applying!"
       #         terraform apply -auto-approve "${COMMON_VARS[@]}"
       #         ;;
@@ -299,57 +297,57 @@ jobs:
       #     esac
       
 
-      # ##### Important - this is a bootstrap workflow
-      # ##### triggering this step with a plan might fail if the other  steps did not run
-      # ##### as the EKS has no public endpoinds and the runner must be alive and available
-      # ##### for the workflow that we trigger in step 4
-      # - name: Step 4 - Trigger Full Main Workflow on Runner
-      #   # cannot run a full PLAN, an apply on step 1+2 is a must
-      #   #if: github.event.inputs.action != 'plan'
-      #   env:
-      #     TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
-      #   run: |
-      #     echo "================================================"
-      #     echo "STEP 4: Triggering Full Main Workflow on Runner"
-      #     echo "Environment: ${{ github.event.inputs.env }}"
-      #     echo "Plan Full Runs: ${{ github.event.inputs.plan_full_runs }}"
-      #     echo "================================================"
+      ##### Important - this is a bootstrap workflow
+      ##### triggering this step with a plan might fail if the other  steps did not run
+      ##### as the EKS has no public endpoinds and the runner must be alive and available
+      ##### for the workflow that we trigger in step 4
+      - name: Step 4 - Trigger Full Main Workflow on Runner
+        # cannot run a full PLAN, an apply on step 1+2 is a must
+        #if: github.event.inputs.action != 'plan'
+        env:
+          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
+        run: |
+          echo "================================================"
+          echo "STEP 4: Triggering Full Main Workflow on Runner"
+          echo "Environment: ${{ github.event.inputs.env }}"
+          echo "Plan Full Runs: ${{ github.event.inputs.plan_full_runs }}"
+          echo "================================================"
           
-      #     # Determine action based on plan_full_runs
-      #     case "${{ github.event.inputs.plan_full_runs }}" in
-      #       true)
-      #         ACTION="plan"
-      #         echo "Triggering main workflow with PLAN action..."
+          # Determine action based on plan_full_runs
+          case "${{ github.event.inputs.plan_full_runs }}" in
+            true)
+              ACTION="plan"
+              echo "Triggering main workflow with PLAN action..."
               
-      #         ;;
-      #       false)
-      #         ACTION="apply"
-      #         echo "Triggering main workflow with APPLY action..."
+              ;;
+            false)
+              ACTION="apply"
+              echo "Triggering main workflow with APPLY action..."
               
-      #         ;;
-      #       *)
-      #         echo "Invalid plan_full_runs value: ${{ github.event.inputs.plan_full_runs }}"
-      #         exit 1
-      #         ;;
-      #     esac
-      #     RUNNER_TYPE="self-hosted"
-      #     # Trigger the main deploy.yml workflow
-      #     curl -X POST \
-      #       -H "Authorization: Bearer $TOKEN_GITHUB" \
-      #       -H "Accept: application/vnd.github+json" \
-      #       "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches" \
-      #       -d "{
-      #         \"ref\": \"main\",
-      #         \"inputs\": {
-      #           \"env\": \"${{ github.event.inputs.env }}\",
-      #           \"action\": \"$ACTION\",
-      #           \"gitops_mode\": \"bootstrap\",
-      #           \"auto_merge\": \"true\",
-      #           \"runner_type\": \"$RUNNER_TYPE\"
-      #         }
-      #       }"
+              ;;
+            *)
+              echo "Invalid plan_full_runs value: ${{ github.event.inputs.plan_full_runs }}"
+              exit 1
+              ;;
+          esac
+          RUNNER_TYPE="self-hosted"
+          # Trigger the main deploy.yml workflow
+          curl -X POST \
+            -H "Authorization: Bearer $TOKEN_GITHUB" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches" \
+            -d "{
+              \"ref\": \"main\",
+              \"inputs\": {
+                \"env\": \"${{ github.event.inputs.env }}\",
+                \"action\": \"$ACTION\",
+                \"gitops_mode\": \"bootstrap\",
+                \"auto_merge\": \"true\",
+                \"runner_type\": \"$RUNNER_TYPE\"
+              }
+            }"
           
-      #     echo "✅ Main workflow triggered successfully with action: $ACTION"
+          echo "✅ Main workflow triggered successfully with action: $ACTION"
 
       - name: Summary
         if: always()
